### ISSUE TITLE
uuidv3s pass as valid

### ISSUE THREAD

**Issue by Mearman** [thenativeweb/uuidv4#265] opened 2020-12-03 08:29 UTC
I've just moved from 6.1.1 to 6.2.5 and now v3 UUIDs such as `a3bb189e-8bf9-3888-9912-ace4e6543002` are passing as valid.

**Comment by goloroden** [comment] 2020-12-03 08:34
Can you please provide a small code example to reproduce this?

**Comment by Mearman** [comment] 2020-12-03 08:36
It's interspersed through a test, but essentially boils down to:
```
import { isUuid } from "uuidv4";
import { assert } from 'chai';

const v3UUID = "a3bb189e-8bf9-3888-9912-ace4e6543002";
assert.isFalse(isUuid(v3UUID))
```

**Comment by goloroden** [comment] 2020-12-03 08:39
Ah okay, sorry… yes. I see what you mean 😊

We have mainly deprecated this package in favour of `uuid`, and most of its functions now simply use theirs. As it seems, the new function is more relaxed. So, unfortunately, since we are going to close this module at some point in the future, it's probably best to directly switch to `uuid` and add another check for that it's actually a `v4` UUID.

I'm sorry that I don't have a better answer here.

**Closed by goloroden** 2020-12-03 08:39 UTC

**Comment by Mearman** [comment] 2020-12-03 08:42
Yeah just saw that.
Not sure how you might want to fix it to maintain legacy support.
